spring:
  application:
    name: organization-service     
  profiles:
    active:
    - dev
  config:
      import: optional:configserver:http://localhost:8888
keycloak:  realm: spmia-realm
  auth-server-url: http://localhost:9090/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: e62dea51-351b-4679-93f0-a13ffbc1af49
  use-resource-role-mappings: true
  bearer-only: true
         
---

spring:
  application:
    name: organization-service     
  profiles:
    active:
    - prod
  cloud:    config:      profile: prod  
  config:
      import: optional:configserver:http://${CONFIG_SERVER}:8888
keycloak:
  realm: spmia-realm
  auth-server-url: http://${KEYCLOAK_SERVER}:9090/auth
  ssl-required: external
  resource: ostock
  credentials:
    secret: ${KEYCLOAK_SECRET}
  use-resource-role-mappings: true
  bearer-only: true         